osx_image: xcode8.2
script: curl "https://api.sightr.io/uploadscript?branch=$TRAVIS_BRANCH&ci=travis&build=$TRAVIS_BUILD_NUMBER&repoKey=594aca5834287328edb4f1be&directory=screenshots&commit=$TRAVIS_COMMIT" | bash
